### ISSUE TITLE
crop_img.py exits on IndexError: list index out of range

### ISSUE THREAD

**Issue by ghost** [IVPLatNU/DeepCovidXR#2]
Hi,

I am attempting to run ```crop_img.py``` on just 2 sample PNG images in one folder through ```crop_img.py``` but it errors out with the following error message
```
  File "crop_img.py", line 467, in lungseg_fromdata
    raw_img = raw_images[i],
IndexError: list index out of range
```

I call crop_img.py like so:
```
$ python crop_img.py -f ../data -U trained_unet_model.hdf5 -o /tmp
```
Where the ```../data``` folder has just two medical images in PNG format.

Any idea what might be causing the error?

**Comment by ghost** [comment]
One cause appears to be supplying a folder name for the ```-f``` option (as per the help) rather than a filename.

**Comment by rmw362** [comment]
Hi Gaby @GabyRumc ,

The issue here is that when the argument is supplied in the terminal as PATH/data without a final slash, the os library interprets this as a filename rather than a directory name, thus the error would be raised unless you supplied the path as PATH/data/ . We have updated all of our source code to normalize pathnames using os.path.normpath so this will not be an issue in the future. You can now supply a folder path with or without the final slash (or using backslashes on Windows as it is OS independent) and you should no longer receive this error. Please let us know if you run into any further issues!

**Comment by rmw362** [comment]
You can also provide a single filename (with absolute path) if you would like to perform cropping on a single image.

**Comment by ghost** [comment]
Yes, I found out by pure chance that I needed to give it a filename rather than a folder (without final slash).
Ok, good that you normalize the path internally now since the (previous) requirement for explicitly ending with a final slash was not documented (and now it doesn't need to be :-)

**Comment by rmw362** [comment]
Great, closing now given this issue is resolved!
